name: GKE Workflow

on:
  pull_request:
    types: [labeled]
jobs:
  gke:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: 'projects/27803622623/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-sa@kamigcp.iam.gserviceaccount.com'
