name: GKE Workflow

on:
  pull_request:
    types: [labeled]
jobs:
  gke:
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        workload_identity_provider: 'projects/27803622623/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'github-sa@kamigcp.iam.gserviceaccount.com'