name: Preview Workflow

on:
  pull_request:
    types: [labeled]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Run preview script
        if: github.event.label.name == 'preview'
        run: echo "My label is ${{ github.event.label.name }}"